

let persona = {
    nombre: 'Carlos' ,
    apellido: 'Padilla',
    edad: 17,
    estudios: ['primarios', 'secundarios'],
    hijos: false,
}
console.log(persona)

console.log(persona.nombre)
console.log(persona.apellido)
console.log(persona.edad)
console.log(persona.estudios)
console.log(persona.estudios[1])
console.log(persona.hijos)


let persona2 = new Object()

persona2.nombre = 'maria'
persona2.apellido = 'estela'
persona2.edad = '84'

console.log(persona2.edad)
